export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGOUT ="LOGOUT"  
export const LOGIN_REQUEST="LOGIN_REQUEST"
export const LOGIN_FAILURE="LOGIN_FAILURE"
export const FETCH_PRODUCTS="FETCH_PRODUCTS"
export const REGISTRATION_REQUEST = 'REGISTRATION_REQUEST';
export const REGISTRATION_SUCCESS = 'REGISTRATION_SUCCESS';
export const REGISTRATION_FAILURE = 'REGISTRATION_FAILURE';